### ISSUE TITLE
Downlevel private fields

### ISSUE THREAD

**Issue by DanielRosenwasser** [sandersn/downlevel-dts#14]
```ts
export declare class C {
  #private: string;
}
```

Proposed emit

```ts
declare const private: unique symbol;

export declare class C {
  private [private]: string
}
```

**Comment by sandersn** [comment]
A couple of small modifications to the proposed output:

1. Multiple #fields emit only one #private per class in 3.8.
2. The symbol's identifier name needs to be uniquified.
3. Neither #fields nor private properties have types in declaration files.

So for an input:

```ts
class C {
  #p = 1
  #q = 2
}
```

You'll get a 3.8 d.ts:

```ts
declare class C {
  #private;
}
```

and the desired downlevel:

```ts
declare const _private_C: unique symbol;
declare class C {
  private [_private_C];
}
```

Note that we need to have the following properties:

1. #p and #q need to be inaccessible.
2. Only C and subclasses of C can be assignable to C.


Here's a couple of options that don't work out:

## Just delete `#private`

This allows assignability from non-C types.

## Just use `private`

```ts
declare class C {
  private "#private"
}
```

This is actually OK. It makes a bogus property available instead of a bogus variable, which is actually better, I think. The property name may also need to be mangled, but it will happen less often.

**Comment by sandersn** [comment]
The likelihood of a class with a normal property named "#private" is extremely low. I'll wait for a real person to complain about the conflict before adding code to avoid it.

```ts
class C {
  #q
  "#private": number
}
```
